/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables;


import org.jooq.*;
import org.jooq.impl.*;

import java.sql.*;
import java.util.*;

import javax.annotation.*;

import jhi.diversify.server.database.*;
import jhi.diversify.server.database.tables.records.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Varietyinplot extends TableImpl<VarietyinplotRecord> {

    /**
     * The reference instance of <code>diversify3.varietyinplot</code>
     */
    public static final Varietyinplot VARIETYINPLOT = new Varietyinplot();
    private static final long serialVersionUID = -1843301117;
    /**
     * The column <code>diversify3.varietyinplot.id</code>.
     */
    public final TableField<VarietyinplotRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");
    /**
     * The column <code>diversify3.varietyinplot.plot_id</code>.
     */
    public final TableField<VarietyinplotRecord, Integer> PLOT_ID = createField("plot_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>diversify3.varietyinplot.variety_id</code>.
     */
    public final TableField<VarietyinplotRecord, Integer> VARIETY_ID = createField("variety_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>diversify3.varietyinplot.rate</code>.
     */
    public final TableField<VarietyinplotRecord, Integer> RATE = createField("rate", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>diversify3.varietyinplot.created_on</code>.
     */
    public final TableField<VarietyinplotRecord, Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");
    /**
     * The column <code>diversify3.varietyinplot.updated_on</code>.
     */
    public final TableField<VarietyinplotRecord, Timestamp> UPDATED_ON = createField("updated_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>diversify3.varietyinplot</code> table reference
     */
    public Varietyinplot() {
        this(DSL.name("varietyinplot"), null);
    }

    /**
     * Create an aliased <code>diversify3.varietyinplot</code> table reference
     */
    public Varietyinplot(String alias) {
        this(DSL.name(alias), VARIETYINPLOT);
    }

    /**
     * Create an aliased <code>diversify3.varietyinplot</code> table reference
     */
    public Varietyinplot(Name alias) {
        this(alias, VARIETYINPLOT);
    }

    private Varietyinplot(Name alias, Table<VarietyinplotRecord> aliased) {
        this(alias, aliased, null);
    }

    private Varietyinplot(Name alias, Table<VarietyinplotRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Varietyinplot(Table<O> child, ForeignKey<O, VarietyinplotRecord> key) {
        super(child, key, VARIETYINPLOT);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VarietyinplotRecord> getRecordType() {
        return VarietyinplotRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Diversify3.DIVERSIFY3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.VARIETYINPLOT_PLOT_ID, Indexes.VARIETYINPLOT_PRIMARY, Indexes.VARIETYINPLOT_VARIETY_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<VarietyinplotRecord, Integer> getIdentity() {
        return Keys.IDENTITY_VARIETYINPLOT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VarietyinplotRecord> getPrimaryKey() {
        return Keys.KEY_VARIETYINPLOT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VarietyinplotRecord>> getKeys() {
        return Arrays.<UniqueKey<VarietyinplotRecord>>asList(Keys.KEY_VARIETYINPLOT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VarietyinplotRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VarietyinplotRecord, ?>>asList(Keys.VARIETYINPLOT_IBFK_1, Keys.VARIETYINPLOT_IBFK_2);
    }

    public Plots plots() {
        return new Plots(this, Keys.VARIETYINPLOT_IBFK_1);
    }

    public Varieties varieties() {
        return new Varieties(this, Keys.VARIETYINPLOT_IBFK_2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Varietyinplot as(String alias) {
        return new Varietyinplot(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Varietyinplot as(Name alias) {
        return new Varietyinplot(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Varietyinplot rename(String name) {
        return new Varietyinplot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Varietyinplot rename(Name name) {
        return new Varietyinplot(name, null);
    }
}
