/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Crops implements Serializable {

    private static final long serialVersionUID = -1272700552;

    private Integer   id;
    private String    cropcommonname;
    private String    croplatinname;
    private Integer   plantpartnerId;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Crops() {}

    public Crops(Crops value) {
        this.id = value.id;
        this.cropcommonname = value.cropcommonname;
        this.croplatinname = value.croplatinname;
        this.plantpartnerId = value.plantpartnerId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Crops(
        Integer   id,
        String    cropcommonname,
        String    croplatinname,
        Integer   plantpartnerId,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.cropcommonname = cropcommonname;
        this.croplatinname = croplatinname;
        this.plantpartnerId = plantpartnerId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCropcommonname() {
        return this.cropcommonname;
    }

    public void setCropcommonname(String cropcommonname) {
        this.cropcommonname = cropcommonname;
    }

    public String getCroplatinname() {
        return this.croplatinname;
    }

    public void setCroplatinname(String croplatinname) {
        this.croplatinname = croplatinname;
    }

    public Integer getPlantpartnerId() {
        return this.plantpartnerId;
    }

    public void setPlantpartnerId(Integer plantpartnerId) {
        this.plantpartnerId = plantpartnerId;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Crops (");

        sb.append(id);
        sb.append(", ").append(cropcommonname);
        sb.append(", ").append(croplatinname);
        sb.append(", ").append(plantpartnerId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
