/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Partners implements Serializable {

    private static final long serialVersionUID = 637984746;

    private Integer   id;
    private String    partnername;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Partners() {}

    public Partners(Partners value) {
        this.id = value.id;
        this.partnername = value.partnername;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Partners(
        Integer   id,
        String    partnername,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.partnername = partnername;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPartnername() {
        return this.partnername;
    }

    public void setPartnername(String partnername) {
        this.partnername = partnername;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Partners (");

        sb.append(id);
        sb.append(", ").append(partnername);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
