/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Plots implements Serializable {

    private static final long serialVersionUID = -69921578;

    private Integer    id;
    private String     plotcode;
    private String     owncode;
    private Integer    siteId;
    private Integer    block;
    private Integer    plot;
    private Integer    subplot;
    private Integer    row;
    private Integer    col;
    private Integer    rep;
    private Integer    subrep;
    private String     management;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private Timestamp  createdOn;
    private Timestamp  updatedOn;

    public Plots() {}

    public Plots(Plots value) {
        this.id = value.id;
        this.plotcode = value.plotcode;
        this.owncode = value.owncode;
        this.siteId = value.siteId;
        this.block = value.block;
        this.plot = value.plot;
        this.subplot = value.subplot;
        this.row = value.row;
        this.col = value.col;
        this.rep = value.rep;
        this.subrep = value.subrep;
        this.management = value.management;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Plots(
        Integer    id,
        String     plotcode,
        String     owncode,
        Integer    siteId,
        Integer    block,
        Integer    plot,
        Integer    subplot,
        Integer    row,
        Integer    col,
        Integer    rep,
        Integer    subrep,
        String     management,
        BigDecimal latitude,
        BigDecimal longitude,
        Timestamp  createdOn,
        Timestamp  updatedOn
    ) {
        this.id = id;
        this.plotcode = plotcode;
        this.owncode = owncode;
        this.siteId = siteId;
        this.block = block;
        this.plot = plot;
        this.subplot = subplot;
        this.row = row;
        this.col = col;
        this.rep = rep;
        this.subrep = subrep;
        this.management = management;
        this.latitude = latitude;
        this.longitude = longitude;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPlotcode() {
        return this.plotcode;
    }

    public void setPlotcode(String plotcode) {
        this.plotcode = plotcode;
    }

    public String getOwncode() {
        return this.owncode;
    }

    public void setOwncode(String owncode) {
        this.owncode = owncode;
    }

    public Integer getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public Integer getBlock() {
        return this.block;
    }

    public void setBlock(Integer block) {
        this.block = block;
    }

    public Integer getPlot() {
        return this.plot;
    }

    public void setPlot(Integer plot) {
        this.plot = plot;
    }

    public Integer getSubplot() {
        return this.subplot;
    }

    public void setSubplot(Integer subplot) {
        this.subplot = subplot;
    }

    public Integer getRow() {
        return this.row;
    }

    public void setRow(Integer row) {
        this.row = row;
    }

    public Integer getCol() {
        return this.col;
    }

    public void setCol(Integer col) {
        this.col = col;
    }

    public Integer getRep() {
        return this.rep;
    }

    public void setRep(Integer rep) {
        this.rep = rep;
    }

    public Integer getSubrep() {
        return this.subrep;
    }

    public void setSubrep(Integer subrep) {
        this.subrep = subrep;
    }

    public String getManagement() {
        return this.management;
    }

    public void setManagement(String management) {
        this.management = management;
    }

    public BigDecimal getLatitude() {
        return this.latitude;
    }

    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    public BigDecimal getLongitude() {
        return this.longitude;
    }

    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Plots (");

        sb.append(id);
        sb.append(", ").append(plotcode);
        sb.append(", ").append(owncode);
        sb.append(", ").append(siteId);
        sb.append(", ").append(block);
        sb.append(", ").append(plot);
        sb.append(", ").append(subplot);
        sb.append(", ").append(row);
        sb.append(", ").append(col);
        sb.append(", ").append(rep);
        sb.append(", ").append(subrep);
        sb.append(", ").append(management);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
