/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Speciesdata implements Serializable {

    private static final long serialVersionUID = -887191026;

    private Integer   id;
    private Integer   datasetId;
    private Integer   traitId;
    private Integer   varietyinplotId;
    private Integer   rep;
    private String    value;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Speciesdata() {}

    public Speciesdata(Speciesdata value) {
        this.id = value.id;
        this.datasetId = value.datasetId;
        this.traitId = value.traitId;
        this.varietyinplotId = value.varietyinplotId;
        this.rep = value.rep;
        this.value = value.value;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Speciesdata(
        Integer   id,
        Integer   datasetId,
        Integer   traitId,
        Integer   varietyinplotId,
        Integer   rep,
        String    value,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.datasetId = datasetId;
        this.traitId = traitId;
        this.varietyinplotId = varietyinplotId;
        this.rep = rep;
        this.value = value;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getDatasetId() {
        return this.datasetId;
    }

    public void setDatasetId(Integer datasetId) {
        this.datasetId = datasetId;
    }

    public Integer getTraitId() {
        return this.traitId;
    }

    public void setTraitId(Integer traitId) {
        this.traitId = traitId;
    }

    public Integer getVarietyinplotId() {
        return this.varietyinplotId;
    }

    public void setVarietyinplotId(Integer varietyinplotId) {
        this.varietyinplotId = varietyinplotId;
    }

    public Integer getRep() {
        return this.rep;
    }

    public void setRep(Integer rep) {
        this.rep = rep;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Speciesdata (");

        sb.append(id);
        sb.append(", ").append(datasetId);
        sb.append(", ").append(traitId);
        sb.append(", ").append(varietyinplotId);
        sb.append(", ").append(rep);
        sb.append(", ").append(value);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
