/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Traits implements Serializable {

    private static final long serialVersionUID = 924696809;

    private Integer   id;
    private String    traitname;
    private String    traitcode;
    private String    unit;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Traits() {}

    public Traits(Traits value) {
        this.id = value.id;
        this.traitname = value.traitname;
        this.traitcode = value.traitcode;
        this.unit = value.unit;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Traits(
        Integer   id,
        String    traitname,
        String    traitcode,
        String    unit,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.traitname = traitname;
        this.traitcode = traitcode;
        this.unit = unit;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTraitname() {
        return this.traitname;
    }

    public void setTraitname(String traitname) {
        this.traitname = traitname;
    }

    public String getTraitcode() {
        return this.traitcode;
    }

    public void setTraitcode(String traitcode) {
        this.traitcode = traitcode;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Traits (");

        sb.append(id);
        sb.append(", ").append(traitname);
        sb.append(", ").append(traitcode);
        sb.append(", ").append(unit);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
