/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.*;
import java.sql.*;

import javax.annotation.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Varietyinplot implements Serializable {

    private static final long serialVersionUID = -1883413154;

    private Integer   id;
    private Integer   plotId;
    private Integer   varietyId;
    private Integer   rate;
    private Timestamp createdOn;
    private Timestamp updatedOn;

    public Varietyinplot() {}

    public Varietyinplot(Varietyinplot value) {
        this.id = value.id;
        this.plotId = value.plotId;
        this.varietyId = value.varietyId;
        this.rate = value.rate;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Varietyinplot(
        Integer   id,
        Integer   plotId,
        Integer   varietyId,
        Integer   rate,
        Timestamp createdOn,
        Timestamp updatedOn
    ) {
        this.id = id;
        this.plotId = plotId;
        this.varietyId = varietyId;
        this.rate = rate;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPlotId() {
        return this.plotId;
    }

    public void setPlotId(Integer plotId) {
        this.plotId = plotId;
    }

    public Integer getVarietyId() {
        return this.varietyId;
    }

    public void setVarietyId(Integer varietyId) {
        this.varietyId = varietyId;
    }

    public Integer getRate() {
        return this.rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Varietyinplot (");

        sb.append(id);
        sb.append(", ").append(plotId);
        sb.append(", ").append(varietyId);
        sb.append(", ").append(rate);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
