/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.*;
import java.math.*;

import javax.annotation.*;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewSiteoverview implements Serializable {

    private static final long serialVersionUID = -1335828250;

    private Integer    traitid;
    private String     traitname;
    private String     traitcode;
    private String     unit;
    private Integer    siteid;
    private String     sitename;
    private String     othername;
    private Integer    datasetid;
    private String     datasetname;
    private Integer    year;
    private BigDecimal avg;
    private BigDecimal min;
    private BigDecimal max;
    private Double     stdv;

    public ViewSiteoverview() {}

    public ViewSiteoverview(ViewSiteoverview value) {
        this.traitid = value.traitid;
        this.traitname = value.traitname;
        this.traitcode = value.traitcode;
        this.unit = value.unit;
        this.siteid = value.siteid;
        this.sitename = value.sitename;
        this.othername = value.othername;
        this.datasetid = value.datasetid;
        this.datasetname = value.datasetname;
        this.year = value.year;
        this.avg = value.avg;
        this.min = value.min;
        this.max = value.max;
        this.stdv = value.stdv;
    }

    public ViewSiteoverview(
        Integer    traitid,
        String     traitname,
        String     traitcode,
        String     unit,
        Integer    siteid,
        String     sitename,
        String     othername,
        Integer    datasetid,
        String     datasetname,
        Integer    year,
        BigDecimal avg,
        BigDecimal min,
        BigDecimal max,
        Double     stdv
    ) {
        this.traitid = traitid;
        this.traitname = traitname;
        this.traitcode = traitcode;
        this.unit = unit;
        this.siteid = siteid;
        this.sitename = sitename;
        this.othername = othername;
        this.datasetid = datasetid;
        this.datasetname = datasetname;
        this.year = year;
        this.avg = avg;
        this.min = min;
        this.max = max;
        this.stdv = stdv;
    }

    public Integer getTraitid() {
        return this.traitid;
    }

    public void setTraitid(Integer traitid) {
        this.traitid = traitid;
    }

    public String getTraitname() {
        return this.traitname;
    }

    public void setTraitname(String traitname) {
        this.traitname = traitname;
    }

    public String getTraitcode() {
        return this.traitcode;
    }

    public void setTraitcode(String traitcode) {
        this.traitcode = traitcode;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public Integer getSiteid() {
        return this.siteid;
    }

    public void setSiteid(Integer siteid) {
        this.siteid = siteid;
    }

    public String getSitename() {
        return this.sitename;
    }

    public void setSitename(String sitename) {
        this.sitename = sitename;
    }

    public String getOthername() {
        return this.othername;
    }

    public void setOthername(String othername) {
        this.othername = othername;
    }

    public Integer getDatasetid() {
        return this.datasetid;
    }

    public void setDatasetid(Integer datasetid) {
        this.datasetid = datasetid;
    }

    public String getDatasetname() {
        return this.datasetname;
    }

    public void setDatasetname(String datasetname) {
        this.datasetname = datasetname;
    }

    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public BigDecimal getAvg() {
        return this.avg;
    }

    public void setAvg(BigDecimal avg) {
        this.avg = avg;
    }

    public BigDecimal getMin() {
        return this.min;
    }

    public void setMin(BigDecimal min) {
        this.min = min;
    }

    public BigDecimal getMax() {
        return this.max;
    }

    public void setMax(BigDecimal max) {
        this.max = max;
    }

    public Double getStdv() {
        return this.stdv;
    }

    public void setStdv(Double stdv) {
        this.stdv = stdv;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewSiteoverview (");

        sb.append(traitid);
        sb.append(", ").append(traitname);
        sb.append(", ").append(traitcode);
        sb.append(", ").append(unit);
        sb.append(", ").append(siteid);
        sb.append(", ").append(sitename);
        sb.append(", ").append(othername);
        sb.append(", ").append(datasetid);
        sb.append(", ").append(datasetname);
        sb.append(", ").append(year);
        sb.append(", ").append(avg);
        sb.append(", ").append(min);
        sb.append(", ").append(max);
        sb.append(", ").append(stdv);

        sb.append(")");
        return sb.toString();
    }
}
