/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewPlotdata implements Serializable {

    private static final long serialVersionUID = 233732844;

    private String     plotcode;
    private Integer    siteid;
    private String     sitename;
    private Integer    id;
    private Integer    plotId;
    private Integer    traitId;
    private Integer    rep;
    private BigDecimal value;
    private Timestamp  createdOn;
    private Timestamp  updatedOn;
    private Integer    datasetid;
    private String     datasetname;
    private Integer    year;
    private String     traitname;
    private String     traitcode;
    private String     unit;

    public ViewPlotdata() {}

    public ViewPlotdata(ViewPlotdata value) {
        this.plotcode = value.plotcode;
        this.siteid = value.siteid;
        this.sitename = value.sitename;
        this.id = value.id;
        this.plotId = value.plotId;
        this.traitId = value.traitId;
        this.rep = value.rep;
        this.value = value.value;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
        this.datasetid = value.datasetid;
        this.datasetname = value.datasetname;
        this.year = value.year;
        this.traitname = value.traitname;
        this.traitcode = value.traitcode;
        this.unit = value.unit;
    }

    public ViewPlotdata(
        String     plotcode,
        Integer    siteid,
        String     sitename,
        Integer    id,
        Integer    plotId,
        Integer    traitId,
        Integer    rep,
        BigDecimal value,
        Timestamp  createdOn,
        Timestamp  updatedOn,
        Integer    datasetid,
        String     datasetname,
        Integer    year,
        String     traitname,
        String     traitcode,
        String     unit
    ) {
        this.plotcode = plotcode;
        this.siteid = siteid;
        this.sitename = sitename;
        this.id = id;
        this.plotId = plotId;
        this.traitId = traitId;
        this.rep = rep;
        this.value = value;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.datasetid = datasetid;
        this.datasetname = datasetname;
        this.year = year;
        this.traitname = traitname;
        this.traitcode = traitcode;
        this.unit = unit;
    }

    public String getPlotcode() {
        return this.plotcode;
    }

    public void setPlotcode(String plotcode) {
        this.plotcode = plotcode;
    }

    public Integer getSiteid() {
        return this.siteid;
    }

    public void setSiteid(Integer siteid) {
        this.siteid = siteid;
    }

    public String getSitename() {
        return this.sitename;
    }

    public void setSitename(String sitename) {
        this.sitename = sitename;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPlotId() {
        return this.plotId;
    }

    public void setPlotId(Integer plotId) {
        this.plotId = plotId;
    }

    public Integer getTraitId() {
        return this.traitId;
    }

    public void setTraitId(Integer traitId) {
        this.traitId = traitId;
    }

    public Integer getRep() {
        return this.rep;
    }

    public void setRep(Integer rep) {
        this.rep = rep;
    }

    public BigDecimal getValue() {
        return this.value;
    }

    public void setValue(BigDecimal value) {
        this.value = value;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Integer getDatasetid() {
        return this.datasetid;
    }

    public void setDatasetid(Integer datasetid) {
        this.datasetid = datasetid;
    }

    public String getDatasetname() {
        return this.datasetname;
    }

    public void setDatasetname(String datasetname) {
        this.datasetname = datasetname;
    }

    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public String getTraitname() {
        return this.traitname;
    }

    public void setTraitname(String traitname) {
        this.traitname = traitname;
    }

    public String getTraitcode() {
        return this.traitcode;
    }

    public void setTraitcode(String traitcode) {
        this.traitcode = traitcode;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewPlotdata (");

        sb.append(plotcode);
        sb.append(", ").append(siteid);
        sb.append(", ").append(sitename);
        sb.append(", ").append(id);
        sb.append(", ").append(plotId);
        sb.append(", ").append(traitId);
        sb.append(", ").append(rep);
        sb.append(", ").append(value);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(datasetid);
        sb.append(", ").append(datasetname);
        sb.append(", ").append(year);
        sb.append(", ").append(traitname);
        sb.append(", ").append(traitcode);
        sb.append(", ").append(unit);

        sb.append(")");
        return sb.toString();
    }
}
