/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewSpeciesdata implements Serializable {

    private static final long serialVersionUID = -945464937;

    private Integer traitid;
    private String  traitname;
    private String  traitcode;
    private Integer siteid;
    private String  sitename;
    private String  partnername;
    private Integer rate;
    private String  cropname;
    private Integer varietyid;
    private String  varietyname;
    private String  value;

    public ViewSpeciesdata() {}

    public ViewSpeciesdata(ViewSpeciesdata value) {
        this.traitid = value.traitid;
        this.traitname = value.traitname;
        this.traitcode = value.traitcode;
        this.siteid = value.siteid;
        this.sitename = value.sitename;
        this.partnername = value.partnername;
        this.rate = value.rate;
        this.cropname = value.cropname;
        this.varietyid = value.varietyid;
        this.varietyname = value.varietyname;
        this.value = value.value;
    }

    public ViewSpeciesdata(
        Integer traitid,
        String  traitname,
        String  traitcode,
        Integer siteid,
        String  sitename,
        String  partnername,
        Integer rate,
        String  cropname,
        Integer varietyid,
        String  varietyname,
        String  value
    ) {
        this.traitid = traitid;
        this.traitname = traitname;
        this.traitcode = traitcode;
        this.siteid = siteid;
        this.sitename = sitename;
        this.partnername = partnername;
        this.rate = rate;
        this.cropname = cropname;
        this.varietyid = varietyid;
        this.varietyname = varietyname;
        this.value = value;
    }

    public Integer getTraitid() {
        return this.traitid;
    }

    public void setTraitid(Integer traitid) {
        this.traitid = traitid;
    }

    public String getTraitname() {
        return this.traitname;
    }

    public void setTraitname(String traitname) {
        this.traitname = traitname;
    }

    public String getTraitcode() {
        return this.traitcode;
    }

    public void setTraitcode(String traitcode) {
        this.traitcode = traitcode;
    }

    public Integer getSiteid() {
        return this.siteid;
    }

    public void setSiteid(Integer siteid) {
        this.siteid = siteid;
    }

    public String getSitename() {
        return this.sitename;
    }

    public void setSitename(String sitename) {
        this.sitename = sitename;
    }

    public String getPartnername() {
        return this.partnername;
    }

    public void setPartnername(String partnername) {
        this.partnername = partnername;
    }

    public Integer getRate() {
        return this.rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

    public String getCropname() {
        return this.cropname;
    }

    public void setCropname(String cropname) {
        this.cropname = cropname;
    }

    public Integer getVarietyid() {
        return this.varietyid;
    }

    public void setVarietyid(Integer varietyid) {
        this.varietyid = varietyid;
    }

    public String getVarietyname() {
        return this.varietyname;
    }

    public void setVarietyname(String varietyname) {
        this.varietyname = varietyname;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewSpeciesdata (");

        sb.append(traitid);
        sb.append(", ").append(traitname);
        sb.append(", ").append(traitcode);
        sb.append(", ").append(siteid);
        sb.append(", ").append(sitename);
        sb.append(", ").append(partnername);
        sb.append(", ").append(rate);
        sb.append(", ").append(cropname);
        sb.append(", ").append(varietyid);
        sb.append(", ").append(varietyname);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
