/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewVarieties implements Serializable {

    private static final long serialVersionUID = 1739685391;

    private Integer id;
    private String  varietyname;
    private String  cropcommonname;
    private String  croplatinname;
    private String  plantpartnername;
    private Long    plots;
    private Long    datapoints;

    public ViewVarieties() {}

    public ViewVarieties(ViewVarieties value) {
        this.id = value.id;
        this.varietyname = value.varietyname;
        this.cropcommonname = value.cropcommonname;
        this.croplatinname = value.croplatinname;
        this.plantpartnername = value.plantpartnername;
        this.plots = value.plots;
        this.datapoints = value.datapoints;
    }

    public ViewVarieties(
        Integer id,
        String  varietyname,
        String  cropcommonname,
        String  croplatinname,
        String  plantpartnername,
        Long    plots,
        Long    datapoints
    ) {
        this.id = id;
        this.varietyname = varietyname;
        this.cropcommonname = cropcommonname;
        this.croplatinname = croplatinname;
        this.plantpartnername = plantpartnername;
        this.plots = plots;
        this.datapoints = datapoints;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getVarietyname() {
        return this.varietyname;
    }

    public void setVarietyname(String varietyname) {
        this.varietyname = varietyname;
    }

    public String getCropcommonname() {
        return this.cropcommonname;
    }

    public void setCropcommonname(String cropcommonname) {
        this.cropcommonname = cropcommonname;
    }

    public String getCroplatinname() {
        return this.croplatinname;
    }

    public void setCroplatinname(String croplatinname) {
        this.croplatinname = croplatinname;
    }

    public String getPlantpartnername() {
        return this.plantpartnername;
    }

    public void setPlantpartnername(String plantpartnername) {
        this.plantpartnername = plantpartnername;
    }

    public Long getPlots() {
        return this.plots;
    }

    public void setPlots(Long plots) {
        this.plots = plots;
    }

    public Long getDatapoints() {
        return this.datapoints;
    }

    public void setDatapoints(Long datapoints) {
        this.datapoints = datapoints;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewVarieties (");

        sb.append(id);
        sb.append(", ").append(varietyname);
        sb.append(", ").append(cropcommonname);
        sb.append(", ").append(croplatinname);
        sb.append(", ").append(plantpartnername);
        sb.append(", ").append(plots);
        sb.append(", ").append(datapoints);

        sb.append(")");
        return sb.toString();
    }
}
