/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.pojos;


import java.io.*;
import java.sql.*;

import javax.annotation.*;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewSpeciesdataTraits implements Serializable {

    private static final long serialVersionUID = -90297270;

    private Integer   id;
    private String    traitname;
    private String    traitcode;
    private String    unit;
    private Timestamp createdOn;
    private Timestamp updatedOn;
    private Long      datapoints;
    private Long      plots;

    public ViewSpeciesdataTraits() {}

    public ViewSpeciesdataTraits(ViewSpeciesdataTraits value) {
        this.id = value.id;
        this.traitname = value.traitname;
        this.traitcode = value.traitcode;
        this.unit = value.unit;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
        this.datapoints = value.datapoints;
        this.plots = value.plots;
    }

    public ViewSpeciesdataTraits(
        Integer   id,
        String    traitname,
        String    traitcode,
        String    unit,
        Timestamp createdOn,
        Timestamp updatedOn,
        Long      datapoints,
        Long      plots
    ) {
        this.id = id;
        this.traitname = traitname;
        this.traitcode = traitcode;
        this.unit = unit;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.datapoints = datapoints;
        this.plots = plots;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTraitname() {
        return this.traitname;
    }

    public void setTraitname(String traitname) {
        this.traitname = traitname;
    }

    public String getTraitcode() {
        return this.traitcode;
    }

    public void setTraitcode(String traitcode) {
        this.traitcode = traitcode;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
    }

    public Long getDatapoints() {
        return this.datapoints;
    }

    public void setDatapoints(Long datapoints) {
        this.datapoints = datapoints;
    }

    public Long getPlots() {
        return this.plots;
    }

    public void setPlots(Long plots) {
        this.plots = plots;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewSpeciesdataTraits (");

        sb.append(id);
        sb.append(", ").append(traitname);
        sb.append(", ").append(traitcode);
        sb.append(", ").append(unit);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(datapoints);
        sb.append(", ").append(plots);

        sb.append(")");
        return sb.toString();
    }
}
