/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jhi.diversify.server.database.tables.Traits;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraitsRecord extends UpdatableRecordImpl<TraitsRecord> implements Record6<Integer, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1522302529;

    /**
     * Create a detached TraitsRecord
     */
    public TraitsRecord() {
        super(Traits.TRAITS);
    }

    /**
     * Getter for <code>diversify3.traits.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Create a detached, initialised TraitsRecord
     */
    public TraitsRecord(Integer id, String traitname, String traitcode, String unit, Timestamp createdOn, Timestamp updatedOn) {
        super(Traits.TRAITS);

        set(0, id);
        set(1, traitname);
        set(2, traitcode);
        set(3, unit);
        set(4, createdOn);
        set(5, updatedOn);
    }

    /**
     * Getter for <code>diversify3.traits.traitname</code>.
     */
    public String getTraitname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diversify3.traits.traitcode</code>.
     */
    public void setTraitcode(String value) {
        set(2, value);
    }

    /**
     * Setter for <code>diversify3.traits.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Setter for <code>diversify3.traits.unit</code>.
     */
    public void setUnit(String value) {
        set(3, value);
    }

    /**
     * Setter for <code>diversify3.traits.traitname</code>.
     */
    public void setTraitname(String value) {
        set(1, value);
    }

    /**
     * Setter for <code>diversify3.traits.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>diversify3.traits.traitcode</code>.
     */
    public String getTraitcode() {
        return (String) get(2);
    }

    /**
     * Getter for <code>diversify3.traits.unit</code>.
     */
    public String getUnit() {
        return (String) get(3);
    }

    /**
     * Getter for <code>diversify3.traits.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Traits.TRAITS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Traits.TRAITS.TRAITNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Traits.TRAITS.TRAITCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Traits.TRAITS.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Traits.TRAITS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Traits.TRAITS.UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTraitname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTraitcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTraitname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTraitcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraitsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraitsRecord value2(String value) {
        setTraitname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraitsRecord value3(String value) {
        setTraitcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraitsRecord value4(String value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraitsRecord value5(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraitsRecord value6(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraitsRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>diversify3.traits.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>diversify3.traits.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(5, value);
    }
}
