/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.records;


import org.jooq.*;
import org.jooq.impl.*;

import java.sql.*;

import javax.annotation.*;

import jhi.diversify.server.database.tables.*;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VarietiesRecord extends UpdatableRecordImpl<VarietiesRecord> implements Record5<Integer, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -657390519;

    /**
     * Create a detached VarietiesRecord
     */
    public VarietiesRecord() {
        super(Varieties.VARIETIES);
    }

    /**
     * Create a detached, initialised VarietiesRecord
     */
    public VarietiesRecord(Integer id, String varietyname, Integer cropId, Timestamp createdOn, Timestamp updatedOn) {
        super(Varieties.VARIETIES);

        set(0, id);
        set(1, varietyname);
        set(2, cropId);
        set(3, createdOn);
        set(4, updatedOn);
    }

    /**
     * Getter for <code>diversify3.varieties.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>diversify3.varieties.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>diversify3.varieties.varietyname</code>.
     */
    public String getVarietyname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diversify3.varieties.varietyname</code>.
     */
    public void setVarietyname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diversify3.varieties.crop_id</code>.
     */
    public Integer getCropId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>diversify3.varieties.crop_id</code>.
     */
    public void setCropId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>diversify3.varieties.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>diversify3.varieties.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(3, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>diversify3.varieties.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>diversify3.varieties.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Varieties.VARIETIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Varieties.VARIETIES.VARIETYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Varieties.VARIETIES.CROP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Varieties.VARIETIES.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Varieties.VARIETIES.UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getVarietyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCropId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getVarietyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCropId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietiesRecord value2(String value) {
        setVarietyname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietiesRecord value3(Integer value) {
        setCropId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietiesRecord value4(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietiesRecord value5(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietiesRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
