/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jhi.diversify.server.database.tables.Varietyinplot;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VarietyinplotRecord extends UpdatableRecordImpl<VarietyinplotRecord> implements Record6<Integer, Integer, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 852143175;

    /**
     * Create a detached VarietyinplotRecord
     */
    public VarietyinplotRecord() {
        super(Varietyinplot.VARIETYINPLOT);
    }

    /**
     * Getter for <code>diversify3.varietyinplot.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Create a detached, initialised VarietyinplotRecord
     */
    public VarietyinplotRecord(Integer id, Integer plotId, Integer varietyId, Integer rate, Timestamp createdOn, Timestamp updatedOn) {
        super(Varietyinplot.VARIETYINPLOT);

        set(0, id);
        set(1, plotId);
        set(2, varietyId);
        set(3, rate);
        set(4, createdOn);
        set(5, updatedOn);
    }

    /**
     * Getter for <code>diversify3.varietyinplot.plot_id</code>.
     */
    public Integer getPlotId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>diversify3.varietyinplot.variety_id</code>.
     */
    public void setVarietyId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>diversify3.varietyinplot.variety_id</code>.
     */
    public Integer getVarietyId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>diversify3.varietyinplot.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>diversify3.varietyinplot.rate</code>.
     */
    public Integer getRate() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>diversify3.varietyinplot.plot_id</code>.
     */
    public void setPlotId(Integer value) {
        set(1, value);
    }

    /**
     * Setter for <code>diversify3.varietyinplot.rate</code>.
     */
    public void setRate(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>diversify3.varietyinplot.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(4);
    }

    /**
     * Getter for <code>diversify3.varietyinplot.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Varietyinplot.VARIETYINPLOT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Varietyinplot.VARIETYINPLOT.PLOT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Varietyinplot.VARIETYINPLOT.VARIETY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Varietyinplot.VARIETYINPLOT.RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Varietyinplot.VARIETYINPLOT.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Varietyinplot.VARIETYINPLOT.UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPlotId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getVarietyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPlotId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getVarietyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietyinplotRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietyinplotRecord value2(Integer value) {
        setPlotId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietyinplotRecord value3(Integer value) {
        setVarietyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietyinplotRecord value4(Integer value) {
        setRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietyinplotRecord value5(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietyinplotRecord value6(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VarietyinplotRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>diversify3.varietyinplot.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Setter for <code>diversify3.varietyinplot.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(5, value);
    }
}
