/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.records;


import org.jooq.*;
import org.jooq.impl.*;

import java.math.*;

import javax.annotation.*;

import jhi.diversify.server.database.tables.*;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewSiteoverviewRecord extends TableRecordImpl<ViewSiteoverviewRecord> implements Record14<Integer, String, String, String, Integer, String, String, Integer, String, Integer, BigDecimal, BigDecimal, BigDecimal, Double> {

    private static final long serialVersionUID = -1620158276;

    /**
     * Create a detached ViewSiteoverviewRecord
     */
    public ViewSiteoverviewRecord() {
        super(ViewSiteoverview.VIEW_SITEOVERVIEW);
    }

    /**
     * Create a detached, initialised ViewSiteoverviewRecord
     */
    public ViewSiteoverviewRecord(Integer traitid, String traitname, String traitcode, String unit, Integer siteid, String sitename, String othername, Integer datasetid, String datasetname, Integer year, BigDecimal avg, BigDecimal min, BigDecimal max, Double stdv) {
        super(ViewSiteoverview.VIEW_SITEOVERVIEW);

        set(0, traitid);
        set(1, traitname);
        set(2, traitcode);
        set(3, unit);
        set(4, siteid);
        set(5, sitename);
        set(6, othername);
        set(7, datasetid);
        set(8, datasetname);
        set(9, year);
        set(10, avg);
        set(11, min);
        set(12, max);
        set(13, stdv);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.traitid</code>.
     */
    public Integer getTraitid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.traitid</code>.
     */
    public void setTraitid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.traitname</code>.
     */
    public String getTraitname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.traitname</code>.
     */
    public void setTraitname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.traitcode</code>.
     */
    public String getTraitcode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.traitcode</code>.
     */
    public void setTraitcode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.unit</code>.
     */
    public String getUnit() {
        return (String) get(3);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.unit</code>.
     */
    public void setUnit(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.siteid</code>.
     */
    public Integer getSiteid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.siteid</code>.
     */
    public void setSiteid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.sitename</code>.
     */
    public String getSitename() {
        return (String) get(5);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.sitename</code>.
     */
    public void setSitename(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.othername</code>.
     */
    public String getOthername() {
        return (String) get(6);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.othername</code>.
     */
    public void setOthername(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.datasetid</code>.
     */
    public Integer getDatasetid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.datasetid</code>.
     */
    public void setDatasetid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.datasetname</code>.
     */
    public String getDatasetname() {
        return (String) get(8);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.datasetname</code>.
     */
    public void setDatasetname(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.YEAR</code>.
     */
    public Integer getYear() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.YEAR</code>.
     */
    public void setYear(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.avg</code>.
     */
    public BigDecimal getAvg() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.avg</code>.
     */
    public void setAvg(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.min</code>.
     */
    public BigDecimal getMin() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.min</code>.
     */
    public void setMin(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>diversify3.view_siteoverview.max</code>.
     */
    public BigDecimal getMax() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.max</code>.
     */
    public void setMax(BigDecimal value) {
        set(12, value);
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>diversify3.view_siteoverview.stdv</code>.
     */
    public Double getStdv() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>diversify3.view_siteoverview.stdv</code>.
     */
    public void setStdv(Double value) {
        set(13, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, String, Integer, String, String, Integer, String, Integer, BigDecimal, BigDecimal, BigDecimal, Double> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, String, String, Integer, String, String, Integer, String, Integer, BigDecimal, BigDecimal, BigDecimal, Double> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.TRAITID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.TRAITNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.TRAITCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.SITEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.SITENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.OTHERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.DATASETID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.DATASETNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.AVG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.MIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field13() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.MAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field14() {
        return ViewSiteoverview.VIEW_SITEOVERVIEW.STDV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getTraitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTraitname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTraitcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getSiteid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSitename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getOthername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getDatasetid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDatasetname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getAvg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component13() {
        return getMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component14() {
        return getStdv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTraitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTraitname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTraitcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSiteid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSitename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getOthername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getDatasetid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDatasetname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getAvg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value13() {
        return getMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value14() {
        return getStdv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value1(Integer value) {
        setTraitid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value2(String value) {
        setTraitname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value3(String value) {
        setTraitcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value4(String value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value5(Integer value) {
        setSiteid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value6(String value) {
        setSitename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value7(String value) {
        setOthername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value8(Integer value) {
        setDatasetid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value9(String value) {
        setDatasetname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value10(Integer value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value11(BigDecimal value) {
        setAvg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value12(BigDecimal value) {
        setMin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value13(BigDecimal value) {
        setMax(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord value14(Double value) {
        setStdv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSiteoverviewRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6, String value7, Integer value8, String value9, Integer value10, BigDecimal value11, BigDecimal value12, BigDecimal value13, Double value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }
}
