/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.records;


import javax.annotation.Generated;

import jhi.diversify.server.database.tables.ViewSpeciesdata;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewSpeciesdataRecord extends TableRecordImpl<ViewSpeciesdataRecord> implements Record10<Integer, String, String, Integer, String, Integer, String, Integer, String, String> {

    private static final long serialVersionUID = 470700107;

    /**
     * Setter for <code>diversify3.view_speciesdata.traitid</code>.
     */
    public void setTraitid(Integer value) {
        set(0, value);
    }

    /**
     * Create a detached ViewSpeciesdataRecord
     */
    public ViewSpeciesdataRecord() {
        super(ViewSpeciesdata.VIEW_SPECIESDATA);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.traitname</code>.
     */
    public void setTraitname(String value) {
        set(1, value);
    }

    /**
     * Create a detached, initialised ViewSpeciesdataRecord
     */
    public ViewSpeciesdataRecord(Integer traitid, String traitname, String traitcode, Integer siteid, String sitename, Integer rate, String cropname, Integer varietyid, String varietyname, String value) {
        super(ViewSpeciesdata.VIEW_SPECIESDATA);

        set(0, traitid);
        set(1, traitname);
        set(2, traitcode);
        set(3, siteid);
        set(4, sitename);
        set(5, rate);
        set(6, cropname);
        set(7, varietyid);
        set(8, varietyname);
        set(9, value);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.traitcode</code>.
     */
    public void setTraitcode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.traitid</code>.
     */
    public Integer getTraitid() {
        return (Integer) get(0);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.traitname</code>.
     */
    public String getTraitname() {
        return (String) get(1);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.traitcode</code>.
     */
    public String getTraitcode() {
        return (String) get(2);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.siteid</code>.
     */
    public Integer getSiteid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.siteid</code>.
     */
    public void setSiteid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.sitename</code>.
     */
    public String getSitename() {
        return (String) get(4);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.sitename</code>.
     */
    public void setSitename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.rate</code>.
     */
    public Integer getRate() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.rate</code>.
     */
    public void setRate(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.cropname</code>.
     */
    public String getCropname() {
        return (String) get(6);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.cropname</code>.
     */
    public void setCropname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.varietyid</code>.
     */
    public Integer getVarietyid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.varietyid</code>.
     */
    public void setVarietyid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.varietyname</code>.
     */
    public String getVarietyname() {
        return (String) get(8);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.varietyname</code>.
     */
    public void setVarietyname(String value) {
        set(8, value);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>diversify3.view_speciesdata.value</code>.
     */
    public String getValue() {
        return (String) get(9);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.value</code>.
     */
    public void setValue(String value) {
        set(9, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.TRAITID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.TRAITNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.TRAITCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Integer, String, Integer, String, Integer, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Integer, String, Integer, String, Integer, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.SITEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.SITENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.CROPNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.VARIETYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getTraitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTraitname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTraitcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.VARIETYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSiteid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSitename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCropname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getVarietyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTraitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTraitname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTraitcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getVarietyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSiteid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSitename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCropname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getVarietyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value1(Integer value) {
        setTraitid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value2(String value) {
        setTraitname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value3(String value) {
        setTraitcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getVarietyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value4(Integer value) {
        setSiteid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value5(String value) {
        setSitename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value6(Integer value) {
        setRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value7(String value) {
        setCropname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value8(Integer value) {
        setVarietyid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value9(String value) {
        setVarietyname(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value10(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, String value7, Integer value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }
}
