/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.records;


import javax.annotation.Generated;

import jhi.diversify.server.database.tables.ViewVarieties;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewVarietiesRecord extends TableRecordImpl<ViewVarietiesRecord> implements Record7<Integer, String, String, String, String, Long, Long> {

    private static final long serialVersionUID = -338447489;

    /**
     * Create a detached ViewVarietiesRecord
     */
    public ViewVarietiesRecord() {
        super(ViewVarieties.VIEW_VARIETIES);
    }

    /**
     * Getter for <code>diversify.view_varieties.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Create a detached, initialised ViewVarietiesRecord
     */
    public ViewVarietiesRecord(Integer id, String varietyname, String cropcommonname, String croplatinname, String plantpartnername, Long plots, Long datapoints) {
        super(ViewVarieties.VIEW_VARIETIES);

        set(0, id);
        set(1, varietyname);
        set(2, cropcommonname);
        set(3, croplatinname);
        set(4, plantpartnername);
        set(5, plots);
        set(6, datapoints);
    }

    /**
     * Getter for <code>diversify.view_varieties.varietyname</code>.
     */
    public String getVarietyname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diversify.view_varieties.cropcommonname</code>.
     */
    public void setCropcommonname(String value) {
        set(2, value);
    }

    /**
     * Setter for <code>diversify.view_varieties.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Setter for <code>diversify.view_varieties.croplatinname</code>.
     */
    public void setCroplatinname(String value) {
        set(3, value);
    }

    /**
     * Setter for <code>diversify.view_varieties.varietyname</code>.
     */
    public void setVarietyname(String value) {
        set(1, value);
    }

    /**
     * Setter for <code>diversify.view_varieties.plantpartnername</code>.
     */
    public void setPlantpartnername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>diversify.view_varieties.cropcommonname</code>.
     */
    public String getCropcommonname() {
        return (String) get(2);
    }

    /**
     * Getter for <code>diversify.view_varieties.croplatinname</code>.
     */
    public String getCroplatinname() {
        return (String) get(3);
    }

    /**
     * Getter for <code>diversify.view_varieties.plots</code>.
     */
    public Long getPlots() {
        return (Long) get(5);
    }

    /**
     * Getter for <code>diversify.view_varieties.plantpartnername</code>.
     */
    public String getPlantpartnername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>diversify.view_varieties.plots</code>.
     */
    public void setPlots(Long value) {
        set(5, value);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewVarieties.VIEW_VARIETIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewVarieties.VIEW_VARIETIES.VARIETYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ViewVarieties.VIEW_VARIETIES.CROPCOMMONNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ViewVarieties.VIEW_VARIETIES.CROPLATINNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewVarieties.VIEW_VARIETIES.PLANTPARTNERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return ViewVarieties.VIEW_VARIETIES.PLOTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return ViewVarieties.VIEW_VARIETIES.DATAPOINTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getVarietyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCropcommonname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCroplatinname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPlantpartnername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getPlots();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getDatapoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getVarietyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCropcommonname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCroplatinname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPlantpartnername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getPlots();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getDatapoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewVarietiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewVarietiesRecord value2(String value) {
        setVarietyname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewVarietiesRecord value3(String value) {
        setCropcommonname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewVarietiesRecord value4(String value) {
        setCroplatinname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewVarietiesRecord value5(String value) {
        setPlantpartnername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewVarietiesRecord value6(Long value) {
        setPlots(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewVarietiesRecord value7(Long value) {
        setDatapoints(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewVarietiesRecord values(Integer value1, String value2, String value3, String value4, String value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>diversify.view_varieties.datapoints</code>.
     */
    public Long getDatapoints() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>diversify.view_varieties.datapoints</code>.
     */
    public void setDatapoints(Long value) {
        set(6, value);
    }
}
