/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.tables.records;


import org.jooq.*;
import org.jooq.impl.*;

import javax.annotation.*;

import jhi.diversify.server.database.tables.*;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewSpeciesdataRecord extends TableRecordImpl<ViewSpeciesdataRecord> implements Record6<Integer, String, String, Integer, String, String> {

    private static final long serialVersionUID = -1024717966;

    /**
     * Create a detached ViewSpeciesdataRecord
     */
    public ViewSpeciesdataRecord() {
        super(ViewSpeciesdata.VIEW_SPECIESDATA);
    }

    /**
     * Create a detached, initialised ViewSpeciesdataRecord
     */
    public ViewSpeciesdataRecord(Integer traitid, String traitname, String traitcode, Integer varietyid, String varietyname, String value) {
        super(ViewSpeciesdata.VIEW_SPECIESDATA);

        set(0, traitid);
        set(1, traitname);
        set(2, traitcode);
        set(3, varietyid);
        set(4, varietyname);
        set(5, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.traitid</code>.
     */
    public Integer getTraitid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.traitid</code>.
     */
    public void setTraitid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.traitname</code>.
     */
    public String getTraitname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.traitname</code>.
     */
    public void setTraitname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.traitcode</code>.
     */
    public String getTraitcode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.traitcode</code>.
     */
    public void setTraitcode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.varietyid</code>.
     */
    public Integer getVarietyid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.varietyid</code>.
     */
    public void setVarietyid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>diversify3.view_speciesdata.varietyname</code>.
     */
    public String getVarietyname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.varietyname</code>.
     */
    public void setVarietyname(String value) {
        set(4, value);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>diversify3.view_speciesdata.value</code>.
     */
    public String getValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>diversify3.view_speciesdata.value</code>.
     */
    public void setValue(String value) {
        set(5, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.TRAITID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.TRAITNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.TRAITCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.VARIETYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.VARIETYNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ViewSpeciesdata.VIEW_SPECIESDATA.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getTraitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTraitname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTraitcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getVarietyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getVarietyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTraitid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTraitname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTraitcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getVarietyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getVarietyname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value1(Integer value) {
        setTraitid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value2(String value) {
        setTraitname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value3(String value) {
        setTraitcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value4(Integer value) {
        setVarietyid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value5(String value) {
        setVarietyname(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord value6(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewSpeciesdataRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }
}
