/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jhi.diversify.server.database.tables.Crops;
import jhi.diversify.server.database.tables.Datasets;
import jhi.diversify.server.database.tables.Partners;
import jhi.diversify.server.database.tables.Plantpartners;
import jhi.diversify.server.database.tables.Plotdata;
import jhi.diversify.server.database.tables.Plots;
import jhi.diversify.server.database.tables.Sites;
import jhi.diversify.server.database.tables.Speciesdata;
import jhi.diversify.server.database.tables.Traits;
import jhi.diversify.server.database.tables.Varieties;
import jhi.diversify.server.database.tables.Varietyinplot;
import jhi.diversify.server.database.tables.ViewPlotdata;
import jhi.diversify.server.database.tables.ViewSiteoverview;
import jhi.diversify.server.database.tables.ViewSites;
import jhi.diversify.server.database.tables.ViewSpeciesdata;
import jhi.diversify.server.database.tables.ViewSpeciesdataTraits;
import jhi.diversify.server.database.tables.ViewVarieties;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Diversify3 extends SchemaImpl {

    private static final long serialVersionUID = -1505202373;

    /**
     * The reference instance of <code>diversify3</code>
     */
    public static final Diversify3 DIVERSIFY3 = new Diversify3();

    /**
     * The table <code>diversify3.crops</code>.
     */
    public final Crops CROPS = jhi.diversify.server.database.tables.Crops.CROPS;

    /**
     * The table <code>diversify3.datasets</code>.
     */
    public final Datasets DATASETS = jhi.diversify.server.database.tables.Datasets.DATASETS;

    /**
     * The table <code>diversify3.partners</code>.
     */
    public final Partners PARTNERS = jhi.diversify.server.database.tables.Partners.PARTNERS;

    /**
     * The table <code>diversify3.plantpartners</code>.
     */
    public final Plantpartners PLANTPARTNERS = jhi.diversify.server.database.tables.Plantpartners.PLANTPARTNERS;

    /**
     * The table <code>diversify3.plotdata</code>.
     */
    public final Plotdata PLOTDATA = jhi.diversify.server.database.tables.Plotdata.PLOTDATA;

    /**
     * The table <code>diversify3.plots</code>.
     */
    public final Plots PLOTS = jhi.diversify.server.database.tables.Plots.PLOTS;

    /**
     * The table <code>diversify3.sites</code>.
     */
    public final Sites SITES = jhi.diversify.server.database.tables.Sites.SITES;

    /**
     * The table <code>diversify3.speciesdata</code>.
     */
    public final Speciesdata SPECIESDATA = jhi.diversify.server.database.tables.Speciesdata.SPECIESDATA;

    /**
     * The table <code>diversify3.traits</code>.
     */
    public final Traits TRAITS = jhi.diversify.server.database.tables.Traits.TRAITS;

    /**
     * The table <code>diversify3.varieties</code>.
     */
    public final Varieties VARIETIES = jhi.diversify.server.database.tables.Varieties.VARIETIES;

    /**
     * The table <code>diversify3.varietyinplot</code>.
     */
    public final Varietyinplot VARIETYINPLOT = jhi.diversify.server.database.tables.Varietyinplot.VARIETYINPLOT;

    /**
     * VIEW
     */
    public final ViewPlotdata VIEW_PLOTDATA = jhi.diversify.server.database.tables.ViewPlotdata.VIEW_PLOTDATA;

    /**
     * VIEW
     */
    public final ViewSiteoverview VIEW_SITEOVERVIEW = jhi.diversify.server.database.tables.ViewSiteoverview.VIEW_SITEOVERVIEW;

    /**
     * VIEW
     */
    public final ViewSites VIEW_SITES = jhi.diversify.server.database.tables.ViewSites.VIEW_SITES;

    /**
     * VIEW
     */
    public final ViewSpeciesdata VIEW_SPECIESDATA = jhi.diversify.server.database.tables.ViewSpeciesdata.VIEW_SPECIESDATA;

    /**
     * VIEW
     */
    public final ViewSpeciesdataTraits VIEW_SPECIESDATA_TRAITS = jhi.diversify.server.database.tables.ViewSpeciesdataTraits.VIEW_SPECIESDATA_TRAITS;

    /**
     * VIEW
     */
    public final ViewVarieties VIEW_VARIETIES = jhi.diversify.server.database.tables.ViewVarieties.VIEW_VARIETIES;

    /**
     * No further instances allowed
     */
    private Diversify3() {
        super("diversify3", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Crops.CROPS,
            Datasets.DATASETS,
            Partners.PARTNERS,
            Plantpartners.PLANTPARTNERS,
            Plotdata.PLOTDATA,
            Plots.PLOTS,
            Sites.SITES,
            Speciesdata.SPECIESDATA,
            Traits.TRAITS,
            Varieties.VARIETIES,
            Varietyinplot.VARIETYINPLOT,
            ViewPlotdata.VIEW_PLOTDATA,
            ViewSiteoverview.VIEW_SITEOVERVIEW,
            ViewSites.VIEW_SITES,
            ViewSpeciesdata.VIEW_SPECIESDATA,
            ViewSpeciesdataTraits.VIEW_SPECIESDATA_TRAITS,
            ViewVarieties.VIEW_VARIETIES);
    }
}
