/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database;


import javax.annotation.Generated;

import jhi.diversify.server.database.routines.ExportTraitDataPlot;
import jhi.diversify.server.database.routines.ExportTraitDataSpecies;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in diversify
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>diversify.export_trait_data_plot</code>
     */
    public static void exportTraitDataPlot(Configuration configuration, String traitids) {
        ExportTraitDataPlot p = new ExportTraitDataPlot();
        p.setTraitids(traitids);

        p.execute(configuration);
    }

    /**
     * Call <code>diversify.export_trait_data_species</code>
     */
    public static void exportTraitDataSpecies(Configuration configuration, String traitids) {
        ExportTraitDataSpecies p = new ExportTraitDataSpecies();
        p.setTraitids(traitids);

        p.execute(configuration);
    }
}
