/*
 * This file is generated by jOOQ.
 */
package jhi.diversify.server.database.routines;


import javax.annotation.Generated;

import jhi.diversify.server.database.Diversify;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExportTraitDataSpecies extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -136814181;

    /**
     * The parameter <code>diversify.export_trait_data_species.traitIds</code>.
     */
    public static final Parameter<String> TRAITIDS = Internal.createParameter("traitIds", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public ExportTraitDataSpecies() {
        super("export_trait_data_species", Diversify.DIVERSIFY);

        addInParameter(TRAITIDS);
    }

    /**
     * Set the <code>traitIds</code> parameter IN value to the routine
     */
    public void setTraitids(String value) {
        setValue(TRAITIDS, value);
    }
}
